### ISSUE TITLE
管理者が解答の送信を試行できる

### ISSUE THREAD

**Issue by keyakko** [ictsc/ictsc-score-server#100]
得点と解答ページ経由で問題ページへ移動した際に、解答欄が表示される。
実際に送信することはできないが、送信を試行することができるため非表示にする。

**Comment by kyontan** [comment]
@keyakko お願いします!

**Comment by keyakko** [comment]
管理者ユーザの場合にフォームを非表示にするよう変更しました！

**Comment by kyontan** [comment]
Ref: #103
