### ISSUE TITLE
満点以上の点数を解答へ与えることができる

### ISSUE THREAD

**Issue by keyakko** [ictsc/ictsc-score-server#106]
現状では、それぞれの問題で満点が決まっているにもかかわらず、満点以上の点数をつけることができる。
そのため、採点者側のミスで満点以上の点を与えてしまう可能性がある。

なので、uiとapiの両方（またはどちらか）で満点以上の点数をつけられないよう、チェックを追加する必要がある。

**Comment by kyontan** [comment]
ICTSC7 ではこれを認めるルールがありましたが、ICTSC8 ではなくなったので、可能であればバリデーションを入れましょう!
(0点未満についても同様)

**Comment by keyakko** [comment]
では、最高点は満点と同じ（ボーナス点は考慮しない）。最低点は０点でUI側実装しますね。

**Comment by kyontan** [comment]
とりあえず保留になりました。
ちなみに実装するときは、入力できる点数の最高点が `answer.perfect_point - SUM(answer.scores.point)` になるので、いい感じに計算する必要があります
