### ISSUE TITLE
writerでログインしたときの挙動が謎

### ISSUE THREAD

**Issue by uplus** [ictsc/ictsc-score-server#164]
### 要修正
* [x] `解答` タブが表示されない
* [x] `ログイン` が永遠に表示される(ログアウト出来ない)
* [x] 問題作成、編集ができない
* [x] 採点できない

### 確認した動作
* 質問解答,解決可能

**Comment by uplus** [comment]
isAdmin(2)とisMember(4)しか無いっぽい
isNoLogin(1), isViewer(5), isWriter(3)がない

競技者, 非競技者 てきなの作ったほうがよさそう(それか運営, 非運営)

**Comment by uplus** [comment]
自分の担当してる問題の解答一覧とかあるとよいと思うので、問題作成時や採点時はadminではなくwriterでやれるようにしたい

**Comment by yatuhashi** [comment]
isAdmin,isWriter,isViewerをまとめたisStaffを作ったので、それで各ページのisAdminを適切に変更すればよさそう。

**Comment by uplus** [comment]
そうします
