### ISSUE TITLE
UTC表示で時間がわかりづらい

### ISSUE THREAD

**Issue by uplus** [ictsc/ictsc-score-server#198]
おそらくUI側でcreated_at,updated_atをそのまま表示してる

**Comment by whywaita** [comment]
JSで手元PCのローカル時刻に変換するように書いてから、これはAPI側で対応すべきなのではという風に思い立った。

ので、 @uplus にDBの値からJSTにするようにお願いした

**Comment by uplus** [comment]
APIのDockerfileでタイムゾーンをJSTにして対応
