### ISSUE TITLE
トランザクション対応

### ISSUE THREAD

**Issue by uplus** [ictsc/ictsc-score-server#270]
全く同じ解答が3連投されたことがあった
クラスタリングにしてると起きやすそう

とりあえず解答投稿時の `最終投稿から指定時間経っているか` ->  `answer.save` までが必要

* [x] FCS.create後にexists -> rollback -> uniq index付けたし平気なはず
* [x] Answerのproblem_id, team_id, created_atでユニーク制約

**Comment by icchy** [comment]
DBクラスタというよりかはAPIサーバーの分散によるものですね（いずれにせよ優先度は低め）

**Comment by uplus** [comment]
少し勘違いしてました。ありがとうございます:pray:
ARはトランザクション サポートしてるようなので解決できそうです
http://railsdoc.com/references/transaction
