### ISSUE TITLE
スポンサー部屋用ページ

### ISSUE THREAD

**Issue by uplus** [ictsc/ictsc-score-server#368]
スポンサー部屋のディスプレイで表示する画面が欲しい

* スコアと問題の解き具合を表示する
* スポンサー部屋にこの一画面を表示すれば情報が分かるようにする
  * 一画面で表示できるサイズに収めるのは厳しいかもしれない 要相談
* participantとno_loginから見えないようにする
  * そもそも他チームが取れる情報はAPI側で制限されてるので問題ない?

このIssueによりグラフページが不要になったらグラフページを削除を消して #307 も閉じていいかもしれない

* [ ] もしUIにあるグラフページを使わないならヘッダーから消す

**Comment by uplus** [comment]
当初はUI側のみでの対応予定でしたが、API側で `/api/summery` みたいなエンドポイントを作ってしまったほうがアクセス制限とか含めて楽かもしれませんね

**Comment by uplus** [comment]
表示するもの候補

* [ ] スコアボード
* [ ] チームごとの解答提出数、問題正答数
* [ ] スコアの遷移グラフ

**Comment by NozomiSugiyama** [comment]
やりたくない
