### ISSUE TITLE
スコアシートを出力するなにかが欲しい

### ISSUE THREAD

**Issue by uplus** [ictsc/ictsc-score-server#376]
### 背景

前回は確か手動でスプレッドシートへ入力して苦労した記憶がある。
0点なのか未提出なのか見分けるのが大変だったり、得点として採用する解答がぱっとは分からなかったりetc...

### やること

横列チームx縦列問題 の表をCSVかなんかで出力できるようにする
エンドポイント増やすつもりはないので多分CLI側で実装

**Comment by kyontan** [comment]
採点表に載せる事項である **問題技術** と **分野** についてもスコアサーバー側で保持する (ユーザには見せない)

問題技術 (`topic`)、分野 (`field`) とかでどうか

**Comment by kyontan** [comment]
お気持ち

||||||エントリーナンバー|
|:-:|:-:|:-:|:-:|:-:|:-:|
||||||学校名|
|問題番号|分野|技術|問題名|満点|

**Comment by uplus** [comment]
#592  一応作ったのでclose
