### ISSUE TITLE
current_userがmember_idなのは少し危険

### ISSUE THREAD

**Issue by uplus** [ictsc/ictsc-score-server#393]
make team and member -> login -> delete team and member で発覚

DBリセットしてからidがずれて競技者のIDがスタッフのIDになるとまずい

**Comment by kyontan** [comment]
auto_increment なら同じIDが裁判されることはないのでは

**Comment by uplus** [comment]
よく覚えてないんですけど ↓みたいな事をすると同じIDが振られました。
開発中はともかく、本番で発生することは無いと思っています。

rake db:setup db:seed_fu
a_1でログイン
rake db:setup
seed_fu以外でユーザーを作成
このときa_1と同じIDを持つユーザーがいると、そのユーザーになる

**Comment by kyontan** [comment]
本番は cookie の secret を変えれば問題ないので close します
