### ISSUE TITLE
Security Alert

### ISSUE THREAD

**Issue by uplus** [ictsc/ictsc-score-server#409]
![2019-02-24 11 55 20 github com 54d79e0bae4f](https://user-images.githubusercontent.com/10358398/53294472-26f74800-382b-11e9-9c15-85d254804977.png)

セキュリティアラート対応お願いします :pray:

**Comment by uplus** [comment]
NozomiSugiyama による調査結果
* kamijinさんが既に対処済みだったので問題なし
* 開発が2016年で止まってるので、別ライブラリへの乗り換えは検討
* GitHubのアラートは消せないっぽいので放置

**Comment by NozomiSugiyama** [comment]
- [SimpleMDE](https://github.com/sparksuite/simplemde-markdown-editor)がはmarkdownのプレビュー時に、[marked](https://github.com/markedjs/marked)を使用しており、`marked` の `sanitize` オプションを `false` している事によってXSSが再現される問題だった。
- 今回のソースではMarkdownのプレビュー時に `marked` を直接使用して `sanitize` オプションを `true` に設定し適切に処理していたため現状、XSSは再現されない。
