### ISSUE TITLE
チーム登録コードのあれを復活させる

### ISSUE THREAD

**Issue by uplus** [ictsc/ictsc-score-server#413]

**Comment by uplus** [comment]
rel #412

**Comment by whywaita** [comment]
merged! https://github.com/ictsc/ictsc-score-server/pull/415

**Comment by uplus** [comment]
手元で適当に試したら治ってなかったので一応reopen

**Comment by uplus** [comment]
確かコンテスト開始前はコントローラのin_compeで弾いていて動かないはず
