### ISSUE TITLE
チーム一覧ページ実装

### ISSUE THREAD

**Issue by uplus** [ictsc/ictsc-score-server#524]
* チーム名・所属を並べる
* 実装はこれを使う https://vuetifyjs.com/en/components/chips
* 予選では可変幅で複数行折り返しで並べる
* 本戦では固定幅1列3つで並べる
* Team#colorがあれば色を付ける
* filter bar
* 本戦ではクリック(かホバー)するとチームメンバーリストがでる

チーム追加・編集UIは後回しで良い(#582 )
メンバー一覧は #523 が実装されてればやる

**Comment by potyama** [comment]
@uplus 
- 本戦では固定幅1列3つで並べる
とありますが、何か理由はあるのでしょうか？

**Comment by uplus** [comment]
> 予選では可変幅で複数行折り返しで並べる
> 本戦では固定幅1列3つで並べる

前者は予選なので参加チーム数が多いため、全て固定幅で表示するとかなり縦長になるので可変幅でずらずらと並べた方が良さそう。
後者は本戦でチーム数もだいたい15なので固定幅で余裕をもたせて表示したほうが良さそう。
って発想です。
基本的にはコスパ考慮してなんとなくでデザインしてます。
