### ISSUE TITLE
/k8sの管理をやめる

### ISSUE THREAD

**Issue by takehaya** [ictsc/ictsc-score-server#619]
## WHY
ざっと理由としては
・現在k8sのクラスタを作るコードを含んでいるが、将来的にこのクラスタの利用は他のアプリに利用される
・k8sのコード管理についてちょっと調べてみたけど、割とマニフェストとアプリケーションは別リポジトリに分離されること多い。
・他のクラスタからの参照や監視等で利用すると考えてるとここを必要ないのに参照してしまうことがあるのでそれここで管理するのは避けたい。

## WHAT
* `k8s` の管理をやめて別リポジトリに移行する

**Comment by takehaya** [comment]
https://github.com/ictsc/ictsc-score-server/pull/570
一旦無事マージされた 🌟

**Comment by takehaya** [comment]
@uplus @takumimoja と思うんですがどうですか？👀

**Comment by uplus** [comment]
良いと思います。
