### ISSUE TITLE
最終スコアをCSVで取得する機能

### ISSUE THREAD

**Issue by kamijin-fanta** [ictsc/ictsc-score-server#63]
`problems?with=answers,score` で情報は取れるはず

**Comment by kyontan** [comment]
ボーナス点の周りの計算も色々あるのでよしなにやる必要がありそう。
シェル芸できる人がいればいいのでは……

採点表を作るときにしか使われないので、わざわざ実装するコストを考えると微妙そうですね。
というわけでクローズします :bow:
